# Generated by Django 4.2.4 on 2023-09-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='media/image_6_us4UWU4.png', upload_to='media'),
        ),
    ]
